import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    title: "Finance Tracker",
    slug: "finance-tracker",
    descriptionKey: "project.finance-tracker.description",
    paragraphKey: "projects.project.finance-tracker.paragraph",
    tech: ["Python", "JavaScript", "Django", "PostgreSQL", "Scikit-learn", "Optuna"],
    picture: "/images/desktop-finance-tracker1.png",
    allPictures: [
      { id: 1, pic: "/images/desktop-finance-tracker1.png" },
      { id: 2, pic: "/images/desktop-finance-tracker2.png"},
      { id: 3, pic: "/images/desktop-finance-tracker3.png"},
      { id: 4, pic: "/images/web-finance-tracker1.png" },
      { id: 5, pic: "/images/web-finance-tracker6.png" },
      { id: 6, pic: "/images/web-finance-tracker7.png" },
      { id: 7, pic: "/images/web-finance-tracker5.png" },
      { id: 8, pic: "/images/web-finance-tracker3.png" },
      { id: 9, pic: "/images/web-finance-tracker4.png" },
      { id: 10, pic: "/images/web-finance-tracker2.png" },
      { id: 11, pic: "/images/finance-tracker1.png" },
      { id: 12, pic: "/images/finance-tracker2.png" },
    ],
    chosenImages: [],
    imageNotes: [ { id: 12, note: "project.finance-tracker.imagenotes" } ],
    imageTexts: "project.finance-tracker.imagetexts",
    demo: "project.finance-tracker.demo",
    isWIP: false,
    isCurrent: false,
    repo: "https://github.com/Stenberg-N/finance-tracker",
    demolink: "https://site--financetracker-app--kwlb8kg8h4nw.code.run/login/?next=/",
  },
  {
    id: 2,
    title: "FocusBoard",
    slug: "focusboard",
    descriptionKey: "project.focusboard.description",
    paragraphKey: "projects.project.focusboard.paragraph",
    tech: ["Svelte", "Rust", "TypeScript", "Tauri"],
    picture: "/images/focusboard5.png",
    allPictures: [
      { id: 1, pic: "/images/focusboard1.png" },
      { id: 2, pic: "/images/focusboard2.png"},
      { id: 3, pic: "/images/focusboard3.png"},
      { id: 4, pic: "/images/focusboard4.png" },
      { id: 5, pic: "/images/focusboard5.png" },
      { id: 6, pic: "/images/focusboard6.png" },
      { id: 7, pic: "/images/focusboard7.png" },
    ],
    chosenImages: [ { id: 1, image: "/images/focusboard1.png" }, { id: 2, image: "/images/focusboard2.png"}, { id: 3, image: "/images/focusboard3.png"}, { id: 5, image: "/images/focusboard5.png" } ],
    imageNotes: [ { id: 5, note: "project.focusboard.imagenotes" } ],
    imageTexts: "project.focusboard.imagetexts",
    demo: "",
    isWIP: true,
    isCurrent: false,
    repo: "https://github.com/Stenberg-N/focusboard",
  },
  {
    id: 3,
    title: "Waste Classifier",
    slug: "waste-classifier",
    descriptionKey: "project.waste-classifier.description",
    paragraphKey: "projects.project.waste-classifier.paragraph",
    tech: ["Python", "PyTorch", "PyQt 6", "Optuna"],
    picture: "/images/waste-classifier4.png",
    allPictures: [
      { id: 1, pic: "/images/waste-classifier1.png" },
      { id: 2, pic: "/images/waste-classifier2.png" },
      { id: 3, pic: "/images/waste-classifier3.png" },
      { id: 4, pic: "/images/waste-classifier4.png" },
      { id: 5, pic: "/images/waste-classifier5.png" },
      { id: 6, pic: "/images/waste-classifier6.png" },
      { id: 7, pic: "/images/waste-classifier7.png" },
    ],
    chosenImages: [],
    imageNotes: [ { id: 3, note: "project.waste-classifier.imagenotes" } ],
    imageTexts: "project.waste-classifier.imagetexts",
    demo: "",
    isWIP: false,
    isCurrent: false,
    repo: "https://github.com/Stenberg-N/waste-classification",
  },
  {
    id: 4,
    title: "FinRadar",
    slug: "fin-radar",
    descriptionKey: "project.fin-radar.description",
    paragraphKey: "projects.project.fin-radar.paragraph",
    tech: ["Svelte", "Rust", "TypeScript", "Tauri"],
    picture: "/images/fin-radar4.png",
    allPictures: [
      { id: 1, pic: "/images/fin-radar1.png" },
      { id: 2, pic: "/images/fin-radar4.png" },
      { id: 3, pic: "/images/fin-radar3.png" },
      { id: 4, pic: "/images/fin-radar2.png" },
      { id: 5, pic: "/images/fin-radar5.png" },
    ],
    chosenImages: [ { id: 1, image: "/images/fin-radar1.png" }, { id: 3, image: "/images/fin-radar3.png" }, { id: 2, image: "/images/fin-radar4.png" }, { id: 5, image: "/images/fin-radar5.png" } ],
    imageNotes: [],
    imageTexts: "project.fin-radar.imagetexts",
    demo: "",
    isWIP: true,
    isCurrent: true,
    repo: "https://github.com/Stenberg-N/fin-radar",
  }
]