import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    title: "Finance Tracker",
    slug: "finance-tracker",
    descriptionKey: "project.finance-tracker.description",
    tech: ["Python", "JavaScript", "Django", "PostgreSQL", "Scikit-learn", "Optuna"],
    picture: "/images/desktop-finance-tracker1.png",
    allPictures: [
      { id: 1, pic: "/images/desktop-finance-tracker1.png" },
      { id: 2, pic: "/images/desktop-finance-tracker2.png"},
      { id: 3, pic: "/images/desktop-finance-tracker3.png"},
      { id: 4, pic: "/images/web-finance-tracker1.png" },
      { id: 5, pic: "/images/web-finance-tracker6.png" },
      { id: 6, pic: "/images/web-finance-tracker7.png" },
      { id: 7, pic: "/images/web-finance-tracker5.png" },
      { id: 8, pic: "/images/web-finance-tracker3.png" },
      { id: 9, pic: "/images/web-finance-tracker4.png" },
      { id: 10, pic: "/images/web-finance-tracker2.png" },
      { id: 11, pic: "/images/finance-tracker1.png" },
      { id: 12, pic: "/images/finance-tracker2.png" },
    ],
    chosenImages: [],
    imageNotes: [],
    imageTexts: "project.finance-tracker.imagetexts",
    demo: "project.finance-tracker.demo",
    isWIP: false,
    isCurrent: false,
  },
  {
    id: 2,
    title: "FocusBoard",
    slug: "focusboard",
    descriptionKey: "project.focusboard.description",
    tech: ["Svelte", "Rust", "TypeScript", "Tauri"],
    picture: "/images/focusboard5.png",
    allPictures: [ { id: 1, pic: "/images/focusboard1.png" }, { id: 2, pic: "/images/focusboard2.png"}, { id: 3, pic: "/images/focusboard3.png"}, { id: 4, pic: "/images/focusboard4.png" }, { id: 5, pic: "/images/focusboard5.png" } ],
    chosenImages: [ { id: 1, image: "/images/focusboard1.png" }, { id: 2, image: "/images/focusboard2.png"}, { id: 3, image: "/images/focusboard3.png"}, { id: 4, image: "/images/focusboard5.png" } ],
    imageNotes: [ { id: 4, note: "project.focusboard.imagenotes" } ],
    imageTexts: "project.focusboard.imagetexts",
    demo: "",
    isWIP: true,
    isCurrent: true,
  },
  {
    id: 3,
    title: "Waste Classifier",
    slug: "waste-classifier",
    descriptionKey: "project.waste-classifier.description",
    tech: ["Python", "PyTorch", "PyQt 6"],
    picture: "/images/waste-classifier1.png",
    allPictures: [],
    chosenImages: [],
    imageNotes: [],
    imageTexts: "project.waste-classifier.imagetexts",
    demo: "",
    isWIP: false,
    isCurrent: false,
  },
]