export const projects = [
  {
    id: 1,
    title: "Finance Tracker",
    slug: "finance-tracker",
    descriptionKey: "project.finance-tracker.description",
    tech: ["Python", "JavaScript", "Django", "PostgreSQL", "Scikit-learn", "Optuna"],
    picture: "/images/desktop-finance-tracker1.png",
    demo: "project.finance-tracker.demo",
    isWIP: false,
    isCurrent: false,
  },
  {
    id: 2,
    title: "FocusBoard",
    slug: "focusboard",
    descriptionKey: "project.focusboard.description",
    tech: ["Svelte", "Rust", "TypeScript", "Tauri"],
    picture: "/images/focusboard5.png",
    demo: "",
    isWIP: true,
    isCurrent: true,
  },
  {
    id: 3,
    title: "Waste Classifier",
    slug: "waste-classifier",
    descriptionKey: "project.waste-classifier.description",
    tech: ["Python", "PyTorch", "PyQt 6"],
    picture: "/images/waste-classifier1.png",
    demo: "",
    isWIP: false,
    isCurrent: false,
  },
]